# Generated by Django 3.1.6 on 2025-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cousreid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('coursedetails', models.CharField(max_length=200)),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
    ]
