# Generated by Django 3.1.6 on 2025-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_title', models.CharField(max_length=20)),
                ('batch_timing', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('faculty_name', models.CharField(max_length=25)),
                ('batch_status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cousreid',
            new_name='courseid',
        ),
    ]
