# Generated by Django 3.1.6 on 2025-06-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20250623_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_id',
            new_name='batchid',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batch_status',
            new_name='batchstatus',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batch_timing',
            new_name='batchtime',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batch_title',
            new_name='batchtitle',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='faculty_name',
            new_name='facultyname',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='start_date',
            new_name='startdate',
        ),
    ]
