# Generated by Django 3.1.6 on 2025-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20250623_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='facultyname',
            field=models.CharField(max_length=30),
        ),
    ]
