# Generated by Django 3.1.6 on 2025-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('admissionno', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.IntegerField()),
                ('emailid', models.CharField(max_length=35)),
                ('admissiondate', models.DateField()),
            ],
        ),
    ]
